# Generated by Django 4.1 on 2022-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DS', 'Dark side'), ('LS', 'Light side')], max_length=2)),
                ('price', models.FloatField(default=100)),
                ('slug', models.SlugField(max_length=200)),
                ('main_image', models.ImageField(upload_to='media/products/')),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
