# Generated by Django 4.1 on 2023-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_customer_order_alter_saber_name_alter_saber_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saber',
            name='main_image',
        ),
        migrations.AddField(
            model_name='saber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
