# Generated by Django 4.1 on 2023-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_saber_main_image_saber_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='saber',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='saber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
